[package]
name = "kindutil"
version = "0.1.1"
edition = "2021"
authors = ["berquerant"]

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2.0"
anyhow = "1.0"