[package]
name = "kindutil"
version = "0.1.0"
edition = "2021"
authors = ["berquerant"]

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
anyhow = "1.0"